### ISSUE TITLE
Tag a stable release?

### ISSUE THREAD

**Issue by dvershinin** [redirectionio/libnginx-mod-redirectionio#1]
If the module is stable/production-ready, can you please tag a stable [release](https://github.com/redirectionio/libnginx-mod-redirectionio/releases)?

**Comment by joelwurtz** [comment]
We have done a lot of modifications recently, there will be a stable release, but we want to finalize testing in our infrastructure first.

**Comment by joelwurtz** [comment]
done as 2.0.0
