### ISSUE TITLE
Weird Safari encoding

### ISSUE THREAD

**Issue by martinsotirov** [redirectionio/libnginx-mod-redirectionio#2]
When we enable the redirection.io nginx module on our server, all the sites behind our nginx reverse proxy display a weird character encoding on Safari:

```
‹­U[Ž›0ýŸU¸ŒÔ¯ò¯€ùh¥¶è.ö%¸cld›I2ëé2ú7«$3šiæQ ö½ç\Ÿ{lªLQ{t¶›«jzr[{½im®©z´@hÚ ­½Ñ¶~áæÝ„åVàæ»¢ÝrKÔ-Þ¸§CAI|òõþ·&Ÿ5ŒvÐH>’o÷¿ŒE7uJ2ƒÒDœVá‚6á6`\YÛÚ¦¹ =ÖÞ-ÇÝ”äª¤EéJÚqf»šá-§èÏŸ—Ür¾¡ °^9˜ YpyC4ŠÚƒaè[5ÒÎçÉ#†ß¡©½UíÝí ã–mBÞÃMØ‚#QÒ„OóƒAn—Z8ÜIäÚ›óÃ)èD”Äû$~æÈçÏÁïçXåûUþVŽ9øo=HÞ¢q’›rAÃ-;lÎñ³KôèÁÜÅ~ZÐÜ¸”È|M`npT ¥kï³³ò©Ú¦s® £%‹ì/3u \ì3‡õfj.§`¹’þ.ðËDüÈp×í|½’é|Òò¹ì£OÃº5Zíê%>Ø÷â°í°G^ÿã2ÎB<2¶±¦C<·k ò,kóuŽ´Œ×ëÒ¢Á8 Æ8@­ŒQšo¹tC*yèÕh¼M.g@Õ(v˜{Ù qêk¥ì4w~¿ªÕ|°ÄhZ{z”–»jÑÄÑ*"XÐ†–ëU™Ò5diðó2+YöK¯Ø(Ü9T…öæÇ?Hµ€†-êƒ‡–aÜ:² -!‰i–”å,†Œµyþâ"ÞÍ1kÕ&IQQ[åQ”¦E±N^¤y‹V=pyjFÌ0hXTæ 8/I‰ÿ‹ Þ~Q¥pqœ3Ùüsúiœ÷­
```

Every other browser including Chrome works fine.

Any ideas what this might be about?

**Comment by martinsotirov** [comment]
I see that a version was released 3 days ago supposedly addressing that problem but we already have v 2.1.1 on our server and the problem is still present.

```
ii  libnginx-mod-redirectionio           1618562287:2.1.1-1
  amd64        Nginx module for redirectionio
ii  redirectionio-agent                  1612262188:2.1.0-1
  amd64        Agent for redirectionio
```

**Comment by joelwurtz** [comment]
The fix was specific to this safari issue, did you restart your nginx server after upgrading ? Our package system does not restart automatically nginx (it's a generally a bad practice to let package do that, user should do it to prevent unwanted downtime).

**Comment by joelwurtz** [comment]
If this is not the case can you provide us an example of your nginx configuration ? We will try to reproduce this problem (you can also email this to support@redirection.io)

**Comment by martinsotirov** [comment]
@joelwurtz our system admin reinstalled the package and restarted nginx again and the problem seems to be solved. Thanks.
